### ISSUE TITLE
Pythonic code - String 

### ISSUE THREAD

**Issue by Julien00859** [Jaenne/mastermind#4]
The following snippet is use in quite a few of your functions:

https://github.com/Jaenne/mastermind/blob/0e303649d05e37d27f2b23322a292bc427867d96/fonctions_mastemind.py#L9-L15

You can rewrite it as follow:

```python
def mode_text():
    return (
        "\nChoose your mode :\n"
        "Hit D to play with duplicates in code.\n"
        "Hit N to play without duplicates in code."
    )
```

When the interpreter reads a string next to another string `"hello" "world"`, it automatically create just one string that is the concatenation of the two. Using parenthesis python is going to ignore the line returns.

Another suggestion is to use triple quotes as follow:

```python
def mode_text():
    return """
Choose your mode :
Hit D to play with duplicates in code.
Hit N to play without duplicates in code."""
```

My personal habit is to use the first for short text when there are not too much line feed and the second for long text. But that's just my habit :yum:

**Comment by laurie-boissay** [comment]
Ok, thank you very much.
